// Auth
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_TOKEN = 'ADD_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';
export const UPDATE_MANAGEMENT = 'UPDATE_MANAGEMENT';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_STATE = 'RESET_STATE';


export const ON_LOGIN = 'ON_LOGIN';
export const GET_CHECKLISTS = 'GET_CHECKLISTS';
export const SAVE_CHECKLIST_CATEGORY = 'SAVE_CHECKLIST_CATEGORY';
export const SAVE_PENDING = 'SAVE_PENDING';
export const REMOVE_PENDING = 'REMOVE_PENDING';
export const SAVE_DRAFT = 'SAVE_DRAFT';
export const REMOVE_DRAFT = 'REMOVE_DRAFT';
export const SET_NETWORK_STATE = 'SET_NETWORK_STATE';
export const GET_INCIDENCES = 'GET_INCIDENCES';


// Canteens
export const GET_CANTEENS = 'GET_CANTEENS';
export const SET_CANTEENS = 'SET_CANTEENS';
export const SET_BUILDINGS = 'SET_BUILDINGS';
export const SET_SELECTED_CANTEEN = 'SET_SELECTED_CANTEEN';
export const SET_FOOD_OFFERS = 'SET_FOOD_OFFERS';
export const SET_SELECTED_CANTEEN_FOOD_OFFERS = 'SET_SELECTED_CANTEEN_FOOD_OFFERS';
export const SET_SELECTED_CANTEEN_FOOD_OFFERS_LOCAL = 'SET_SELECTED_CANTEEN_FOOD_OFFERS_LOCAL';
export const SET_BUSINESS_HOURS = 'SET_BUSINESS_HOURS';
export const SET_SELECTED_FOOD_MARKINGS = 'SET_SELECTED_FOOD_MARKINGS';
export const SET_CANTEEN_FEEDBACK_LABELS = 'SET_CANTEEN_FEEDBACK_LABELS';
export const SET_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES = 'SET_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';
export const UPDATE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES = 'UPDATE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';
export const DELETE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES = 'DELETE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';

// Settings
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_WARNING = 'SET_WARNING';
export const SET_SORTING = 'SET_SORTING';

// Food Feedback Labels
export const SET_FOOD_CATEGORIES = 'SET_FOOD_CATEGORIES';
export const SET_FOOD_OFFERS_CATEGORIES = 'SET_FOOD_OFFERS_CATEGORIES';
export const UPDATE_FOOD_FEEDBACK_LABELS = 'UPDATE_FOOD_FEEDBACK_LABELS';
export const UPDATE_OWN_FOOD_FEEDBACK = 'UPDATE_OWN_FOOD_FEEDBACK';
export const UPDATE_FOOD_FEEDBACK_LOCAL = 'UPDATE_FOOD_FEEDBACK_LOCAL';
export const DELETE_FOOD_FEEDBACK_LOCAL = 'DELETE_FOOD_FEEDBACK_LOCAL';
export const UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES = 'UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES';
export const UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL = 'UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL';
export const DELETE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL = 'DELETE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL';
export const UPDATE_MARKINGS = 'UPDATE_MARKINGS';
export const SET_MARKING_DETAILS = 'SET_MARKING_DETAILS';